title: Remco Kranenburg
description: Google Summer of Code participant for xrdesktop
show_downloads: true

url: "https://remcokranenburg.com"

google_analytics:

date_format: "%Y-%m-%d %H:%M:%S"

theme: # leave it empty

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'contact']
