title: Remco's Blog
description: Google Summer of Code 2021 participant with xrdesktop
author: Remco Kranenburg

url: "https://remcokranenburg.com"

date_format: "%Y-%m-%d"

theme: # leave it empty

plugins:
  - jekyll-target-blank
  - jekyll-feed

target-blank:
    rel: nofollow

header_page_refs: ['about', 'contact']
