title: Remco's Blog
description: Code and stuff
author: Remco Kranenburg

url: "https://remcokranenburg.com"

date_format: "%Y-%m-%d"

theme: # leave it empty

collections:
  tags:
    output: true
    permalink: tag/:title/

plugins:
  - jekyll-target-blank
  - jekyll-feed

target-blank:
    rel: nofollow

header_page_refs: ['about', 'tags']
