title: Remco Kranenburg
description: Google Summer of Code participant for xrdesktop
show_downloads: true

url: "https://remcokranenburg.com"

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'contact']
